### PR TITLE
Remove pesudo-field contentDescription and its use in Poll view.

### PR DESCRIPTION
**Pull request by khink**
This made the poll question appear twice in the Poll view.

contentDescription is not used anywhere else in the code, and is not something the class needs to provide.

I think it's safe to remove it altogether.

### CODE REVIEW

**Comment by khink** [comment]
@pbauer @sneridagh @bsuttor @boulch Someone want to say something about this?

**Comment by bsuttor** [comment]
LGTM

**Comment by khink** [comment]
@jcbrand @sneridagh Someone feel like making a release?

**Comment by khink** [comment]
https://pypi.python.org/pypi/Products.PlonePopoll/2.8b2

**Pull request merged**
